backend:
  name: github
  repo: your-username/client-guides
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "clients"
    label: "Client Guides"
    folder: "content/clients"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "shared"
    label: "Shared Content"
    folder: "content/shared"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
