name: Build and Deploy on Content Change

on:
  push:
    branches: [main]
    paths:
      - 'content/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Needed to allow GitHub Actions to push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build site with Eleventy
        run: npx @11ty/eleventy

      - name: Commit and push built docs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git diff --quiet --cached || git commit -m "Auto-build from content update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
