name: Build and Deploy on Shared Content Change

on:
  push:
    branches: [main]
    paths:
      - 'content/shared/**'
      - '_includes/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build site with Eleventy
        run: npx @11ty/eleventy

      - name: Commit and push changes to docs folder
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git add docs
          git diff --quiet --cached || git commit -m "Auto-build from shared content update"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main
